---
title: "WorldFreedomIndex"
author: "Jeff Grayum"
date: "3/27/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(janitor)
theme_set(theme_tufte())
```

Importing data.
```{r}
tuesdata <- tidytuesdayR::tt_load('2022-02-22')

freedom <- tuesdata$freedom %>%
  clean_names() %>%
  rename(civil_liberties = cl,
         political_rights = pr)

freedom %>% 
  view()

freedom %>%
  count(year, sort = TRUE) %>%
  arrange(desc(year))

freedom %>%
  distinct(country, region_name) %>%
  view()
```


```{r}
freedom %>%
  ggplot(aes(civil_liberties)) +
  geom_histogram() +
  theme_hc() +
  labs(x = "Civil liberties",
       y = "Count")

freedom %>%
  filter(year == 2020) %>%
  arrange(desc(civil_liberties))

by_region <- freedom %>%
  filter(year == 2020) %>%
  group_by(region_name) %>%
  summarize(n_countries = n(),
            avg_civil_liberties = mean(civil_liberties),
            avg_political_rights = mean(political_rights),
            pct_free = mean(status == "F"))

by_region %>%
  ggplot(aes(avg_civil_liberties, avg_political_rights, size = n_countries)) +
  geom_point()  +
  geom_text(aes(label = region_name), vjust = 1, hjust = 1) +
  geom_abline(color = "red") + 
  expand_limits(x = 0, y = 0, size = 0) +
  labs(x = "Avg civil liberties",
       y = "Avg political rights",
       size = "# of countries") 

freedom %>%
  filter(country == "United States of America") %>%
  ggplot(aes(year, civil_liberties)) +
  geom_line()

```


```{r}
freedom %>%
 ggplot(aes(civil_liberties, political_rights)) +
  geom_jitter()  +
  #geom_text(aes(label = region_name), vjust = 1, hjust = 1) +
  geom_abline(color = "red") + 
  expand_limits(x = 0, y = 0, size = 0) +
  labs(x = "Avg civil liberties",
       y = "Avg political rights",
       size = "# of countries") 

freedom %>%
  filter(year == 2020) %>%
  ggplot(aes(civil_liberties, political_rights)) +
  geom_jitter(height = 0.2, width = 0.2) +
  geom_abline(color = "red") + 
  expand_limits(x = 0, y = 0, size = 0) +
  labs(x = "Avg civil liberties",
       y = "Avg political rights",
       size = "# of countries") 

freedom %>%
  summarize(sd(civil_liberties),
            sd(political_rights))

freedom %>%
  filter(year == 2020) %>%
  gather(metric, value, civil_liberties, political_rights) %>%
  mutate(metric = str_to_title(str_replace_all(metric, "_", " ")),
         region_name = fct_reorder(region_name, value)) %>%
  count(region_name, metric, value) %>%
  ggplot(aes(value, n)) +
  geom_col() +
  facet_grid(region_name ~ metric) +
  labs(x = "World Freedom Index Rating",
       y = "# of countries",
       title = "Distribution of Freedom Index by region")
```

```{r}
freedom %>%
  gather(metric, value, civil_liberties, political_rights) %>%
  mutate(metric = str_to_title(str_replace_all(metric, "_", " ")),
         region_name = fct_reorder(region_name, value)) %>%
  group_by(year, region_name, metric) %>%
  summarize(avg_rating = mean(value)) %>%
  ggplot(aes(year, avg_rating, color = region_name)) +
  geom_line() +
  expand_limits(y = 1) +
  scale_y_reverse(breaks = seq(1,7)) +
  facet_wrap(~ metric) +
  labs(x = "Year",
       y = "WFI rating",
       title = "Distribution of Freedom Index over time by region",
       color = "Region")

freedom_gathered <- freedom %>%
  gather(metric, value, civil_liberties, political_rights) %>%
  mutate(metric = str_to_title(str_replace_all(metric, "_", " ")),
        region_name = fct_reorder(region_name, value))

overall <- freedom_gathered %>%
  group_by(year, metric) %>%
  summarize(avg_rating = mean(value))

freedom_gathered %>%
  group_by(year, region_name, metric) %>%
  summarize(avg_rating = mean(value)) %>%
  ggplot(aes(year, avg_rating)) +
  geom_line(aes(color = region_name)) +
  geom_line(data = overall, size = 1.5) +
  expand_limits(y = 1) +
  scale_y_reverse(breaks = seq(1,7)) +
  facet_wrap(~ metric) +
  labs(x = "Year",
       y = "WFI rating",
       title = "Distribution of Freedom Index over time by region",
       color = "Region",
       subtitle = "Black line shows overall trend")

```


